# Generated by Django 4.2.1 on 2023-05-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_hire', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('public_service_no', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('fuel_received', models.FloatField()),
                ('fuel_sold', models.FloatField()),
                ('fuel_remaining', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Ctravels.employees')),
            ],
        ),
        migrations.CreateModel(
            name='FuelVendors',
            fields=[
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Ctravels.employees')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField(max_length=255)),
                ('unit_price', models.FloatField(default=0)),
                ('total_fuel', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.fuelstations')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('number_plate', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('year', models.DateField()),
                ('current_millage', models.CharField(max_length=100)),
                ('last_service_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.TextField(max_length=500)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('mechanic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.mechanics')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('notification_message', models.TextField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuelRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('unit_price', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.fuelstations')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.vehicles')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.driver')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.fuelvendors')),
            ],
        ),
        migrations.CreateModel(
            name='StationFuelRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_remaining', models.FloatField(default=0)),
                ('fuel_received', models.FloatField(default=0)),
                ('date_received', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('unit_price', models.FloatField(default=0)),
                ('buying_cost', models.FloatField(default=0)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.fuelstations')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.fuelvendors')),
            ],
        ),
        migrations.CreateModel(
            name='DriversFuelOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.vehicles')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ctravels.vehicles'),
        ),
    ]
