# Generated by Django 4.2.1 on 2023-05-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ctravels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='driver',
        ),
        migrations.AlterModelTable(
            name='driversfuelorders',
            table='drivers fuel orders',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='fuelstations',
            table='fuel stations',
        ),
        migrations.AlterModelTable(
            name='fuelvendors',
            table='fuel vendors',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
        migrations.AlterModelTable(
            name='mechanics',
            table='mechanics',
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='repair',
            table='repairs',
        ),
        migrations.AlterModelTable(
            name='stationfuelrefill',
            table='station fuel refill',
        ),
        migrations.AlterModelTable(
            name='vehiclefuelrefill',
            table='vehicles fuel refill',
        ),
        migrations.AlterModelTable(
            name='vehicles',
            table='vehicles',
        ),
    ]
