# Generated by Django 4.2.1 on 2023-05-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ctravels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='DriversFuelOrders',
            new_name='DriversFuelOrder',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='FuelStations',
            new_name='FuelStation',
        ),
        migrations.RenameModel(
            old_name='FuelVendors',
            new_name='FuelVendor',
        ),
        migrations.RenameModel(
            old_name='Mechanics',
            new_name='Mechanic',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
